POST https://foyez-realworld-api.herokuapp.com/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "test2@email.com",
    "password": "testpass"
  }
}

###

POST https://foyez-realworld-api.herokuapp.com/api/users
Content-Type: application/json

{
  "user": {
    "username": "test2",
    "email": "test2@email.com",
    "password": "testpass"
  }
}